name: Build Template Base Image

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-template-base.yml'
  workflow_dispatch:

env:
  REGISTRY: us-west1-docker.pkg.dev/proximal-core-0/environments
  IMAGE_NAME: fetchr-template-base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure Docker to use gcloud credentials
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push template base
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          
          docker buildx build \
            --platform linux/amd64 \
            -t ${IMAGE}:latest \
            -t ${IMAGE}:${{ github.sha }} \
            --push \
            .
            
      - name: Get image digest
        id: digest
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          DIGEST=$(docker buildx imagetools inspect ${IMAGE}:latest --format '{{json .}}' | jq -r '.manifest.digest')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "📦 Built image: ${IMAGE}@${DIGEST}"
          
      - name: Output digest for environment updates
        run: |
          echo "### Template Base Updated 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Digest:** `${{ steps.digest.outputs.digest }}`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Update environment Dockerfiles to use:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`dockerfile" >> $GITHUB_STEP_SUMMARY
          echo "FROM ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.digest.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
